<a href="https://colab.research.google.com/github/MuhammadUmarAshrafDE/Machine-Learning/blob/main/ML_Reducing_Noise_Anomaly_ded.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.ensemble import IsolationForest

In [ ]:
#Noise deduction
data = np.array([1,2,3,4,5,6,7,8,9,10])
window_size = 4
moving_average = np.convolve(data, np.ones(window_size), 'valid') / window_size
print(moving_average)

[2.5 3.5 4.5 5.5 6.5 7.5 8.5]


In [ ]:
#Anomly

data = [[-1.1],[0.3],[0.5],[-2.1]]

#train isolation forest model
clf=IsolationForest(random_state=0)

#fit the model
clf.fit(data)

#predict
pred = clf.predict(data)

#display results
print(pred)


[ 1  1  1 -1]


In [ ]:
#Outlier Deduction Using DBSCAN (Density Based Spatial Clustering of Applications with Noise)
from sklearn.cluster import DBSCAN

data = [[1,2],[2,2],[2,3],[8,7],[8,8],[25,80]]
clustering = DBSCAN(eps=3, min_samples=2).fit_predict(data)
print(clustering)


[ 0  0  0  1  1 -1]
